import { defineCanonicalSkill } from "../../define.ts";
import type { CanonicalSkillDefinition } from "../../types.ts";

export const SURE_TRANS_CANONICAL: CanonicalSkillDefinition = defineCanonicalSkill({
	schema: "sure.canonical.skill.v1",
	skill_id: "sure_trans",
	command_id: "sure-trans",
	distribution_slug: "sure-trans",
	display_name: "SURE Trans",
	description: "Transform a Docker or locked Python model runtime into a SURE Eval deployment bundle.",
	workflow: {
		schema: "sure.workflow.definition.v1",
		workflow_id: "sure_trans",
		version: "legacy-v1",
		checkpoint_id: "main_flow",
		checkpoint_label: "SURE model transformation state machine",
		branches: [
			{
				id: "main",
				units: [
					{
						id: "load_trans_input",
						label: "Load transformation input",
						kind: "gate",
						produces: "trans_input_resolved.json",
						schema_ref: "trans_input_resolved.schema.json",
						required_fields: [
							"source_kind",
							"build_context",
							"model_path",
							"inference_entrypoint",
							"framework",
							"model_framework",
							"model_name",
							"model_dir",
							"task_type",
							"device",
							"package_profile",
						],
						allowed_values: {
							source_kind: ["docker", "python"],
							framework: ["pytorch"],
							task_type: ["asr", "s2tt", "tts", "vc"],
							device: ["auto", "cuda", "cpu"],
							package_profile: ["docker-registry", "none"],
						},
						gate: {
							validator_id: "python-script",
							backend_operation_id: "sure.trans.validate_input",
							script_id: "check_artifact.py",
							script_args: ["--kind", "input"],
						},
						owned_scripts: ["materialize_trans_inputs.py"],
					},
					{
						id: "inspect_dependencies",
						label: "Inspect inference dependencies",
						kind: "gate",
						produces: "inference_dependency_report.json",
						schema_ref: "inference_dependency_report.schema.json",
						required_fields: [
							"entrypoint",
							"build_context",
							"docker_copy_sources",
							"python_imports",
							"support_paths",
							"unresolved",
							"external_paths",
							"status",
						],
						gate: {
							validator_id: "python-script",
							backend_operation_id: "sure.trans.validate_dependencies",
							script_id: "check_artifact.py",
							script_args: ["--kind", "dependencies"],
						},
						owned_scripts: ["inspect_dependencies.py"],
					},
					{
						id: "detect_framework",
						label: "Validate framework",
						kind: "gate",
						produces: "framework_detection.json",
						schema_ref: "framework_detection.schema.json",
						required_fields: [
							"declared_framework",
							"declared_model_framework",
							"detected_framework",
							"detected_model_framework",
							"framework_requirement_met",
							"model_framework_matches",
							"transformers_preferred",
							"clarification_required",
							"architecture_signals",
							"architecture_clarification",
							"status",
							"evidence",
						],
						allowed_values: {
							declared_framework: ["pytorch"],
							detected_framework: ["pytorch", "tensorflow", "jax_flax", "unknown"],
							detected_model_framework: ["transformers", "custom", "unknown"],
						},
						gate: {
							validator_id: "python-script",
							backend_operation_id: "sure.trans.validate_framework",
							script_id: "check_artifact.py",
							script_args: ["--kind", "framework"],
						},
						owned_scripts: ["detect_framework.py"],
					},
					{
						id: "prepare_fixture",
						label: "Prepare bounded smoke fixture",
						kind: "gate",
						produces: "fixture_manifest.json",
						schema_ref: "fixture_manifest.schema.json",
						required_fields: [
							"status",
							"model_id",
							"model_name",
							"model_dir",
							"task_type",
							"source_dir",
							"staged_dir",
							"gt_jsonl",
							"samples",
							"source_path",
							"staged_path",
							"sha256",
							"gt_sha256",
							"expected_sha256",
							"sample_count",
							"annotation_source",
						],
						gate: {
							validator_id: "python-script",
							backend_operation_id: "sure.trans.validate_fixture",
							script_id: "check_artifact.py",
							script_args: ["--kind", "fixture"],
						},
						owned_scripts: ["prepare_fixture.py"],
					},
					{
						id: "build_source_image",
						label: "Materialize source runtime",
						kind: "gate",
						produces: "source_image_result.json",
						schema_ref: "source_image_result.schema.json",
						required_fields: ["status"],
						gate: {
							validator_id: "python-script",
							script_id: "run_docker_build.py",
						},
						owned_scripts: ["run_docker_build.py"],
					},
					{
						id: "validate_env_compat",
						label: "Validate source execution compatibility",
						kind: "gate",
						produces: "execution_compat.json",
						schema_ref: "execution_compat.schema.json",
						required_fields: ["status"],
						gate: {
							validator_id: "python-script",
							script_id: "run_execution_compat.py",
						},
						owned_scripts: ["vc_exec.py"],
					},
					{
						id: "validate_original_inference",
						label: "Validate original inference baseline",
						kind: "gate",
						produces: "original_inference_result.json",
						schema_ref: "original_inference_result.schema.json",
						required_fields: ["status", "input", "run_command"],
						gate: {
							validator_id: "python-script",
							script_id: "run_trans_validate.py",
							script_args: ["--kind", "original_inference"],
						},
					},
					{
						id: "stage_model_payload",
						label: "Stage model payload",
						kind: "gate",
						produces: "model_payload_manifest.json",
						schema_ref: "model_payload_manifest.schema.json",
						required_fields: [
							"status",
							"source",
							"destination",
							"policy",
							"file_count",
							"total_bytes",
							"files",
							"payload_identity_sha256",
						],
						gate: {
							validator_id: "python-script",
							backend_operation_id: "sure.trans.validate_model_payload",
							script_id: "check_artifact.py",
							script_args: ["--kind", "model_payload"],
						},
						owned_scripts: ["stage_model_payload.py"],
					},
					{
						id: "generate_adapter",
						label: "Generate SURE adapter",
						kind: "gate",
						produces: "adapter_manifest.json",
						schema_ref: "adapter_manifest.schema.json",
						required_fields: [
							"status",
							"strategy",
							"runtime_kind",
							"model_py",
							"init_py",
							"validate_py",
							"server_py",
							"config_yaml",
							"model_spec",
							"io_contract",
							"python_executable",
							"server_command",
							"working_dir",
						],
						gate: {
							validator_id: "python-script",
							backend_operation_id: "sure.trans.validate_adapter",
							auxiliary_validator_ids: ["legacy-in-process"],
							script_id: "check_artifact.py",
							script_args: ["--kind", "adapter"],
						},
						owned_scripts: ["scaffold_adapter.py"],
					},
					{
						id: "build_adapter_image",
						label: "Materialize Eval adapter runtime",
						kind: "gate",
						produces: "adapter_image_result.json",
						schema_ref: "adapter_image_result.schema.json",
						required_fields: ["status", "server_command", "working_dir"],
						gate: {
							validator_id: "python-script",
							backend_operation_id: "sure.trans.validate_adapter_image",
							script_id: "check_artifact.py",
							script_args: ["--kind", "adapter_image"],
						},
						owned_scripts: ["materialize_adapter_runtime.py"],
					},
					{
						id: "validate_import",
						label: "Validate adapter import",
						kind: "gate",
						produces: "import_result.json",
						schema_ref: "import_result.schema.json",
						required_fields: ["status", "run_command"],
						gate: {
							validator_id: "python-script",
							script_id: "run_trans_validate.py",
							script_args: ["--kind", "import"],
						},
					},
					{
						id: "validate_load",
						label: "Validate persistent model load",
						kind: "gate",
						produces: "load_result.json",
						schema_ref: "load_result.schema.json",
						required_fields: ["status", "run_command"],
						gate: {
							validator_id: "python-script",
							script_id: "run_trans_validate.py",
							script_args: ["--kind", "load"],
						},
					},
					{
						id: "validate_infer",
						label: "Validate adapter inference",
						kind: "gate",
						produces: "infer_result.json",
						schema_ref: "infer_result.schema.json",
						required_fields: ["status", "input", "run_command"],
						gate: {
							validator_id: "python-script",
							script_id: "run_trans_validate.py",
							script_args: ["--kind", "infer"],
						},
					},
					{
						id: "validate_contract",
						label: "Validate adapter output contract",
						kind: "gate",
						produces: "contract_result.json",
						schema_ref: "contract_result.schema.json",
						required_fields: ["status", "run_command"],
						gate: {
							validator_id: "python-script",
							script_id: "run_trans_validate.py",
							script_args: ["--kind", "contract"],
						},
					},
					{
						id: "validate_mcp",
						label: "Validate MCP protocol",
						kind: "gate",
						produces: "mcp_result.json",
						schema_ref: "mcp_result.schema.json",
						required_fields: ["status", "tool_name", "run_command"],
						gate: {
							validator_id: "python-script",
							script_id: "run_trans_validate.py",
							script_args: ["--kind", "mcp"],
						},
						owned_scripts: ["mcp_smoke.py"],
					},
					{
						id: "validate_equivalence",
						label: "Compare original and MCP inference",
						kind: "gate",
						produces: "equivalence_result.json",
						schema_ref: "equivalence_result.schema.json",
						required_fields: ["status", "baseline_output", "adapter_output", "run_command"],
						gate: {
							validator_id: "python-script",
							script_id: "run_trans_validate.py",
							script_args: ["--kind", "equivalence"],
						},
					},
					{
						id: "package_container",
						label: "Package validated runtime",
						kind: "gate",
						produces: "docker_registry_result.json",
						schema_ref: "docker_registry_result.schema.json",
						required_fields: ["schema", "status"],
						gate: {
							validator_id: "python-script",
							backend_operation_id: "sure.trans.validate_package_container",
							script_id: "check_artifact.py",
							script_args: ["--kind", "registry"],
						},
						owned_scripts: ["vc_exec.py", "mcp_smoke.py", "package_python_runtime.py"],
					},
					{
						id: "write_runtime_inventory",
						label: "Write Eval runtime inventory",
						kind: "gate",
						produces: "runtime_inventory.json",
						schema_ref: "runtime_inventory.schema.json",
						required_fields: ["schema", "status", "model", "container_runtime", "weights", "readiness", "policy"],
						gate: {
							validator_id: "python-script",
							backend_operation_id: "sure.trans.validate_runtime_inventory",
							script_id: "check_artifact.py",
							script_args: ["--kind", "runtime_inventory"],
						},
						owned_scripts: ["write_runtime_inventory.py"],
					},
					{
						id: "verdict",
						label: "Write transformation verdict",
						kind: "gate",
						produces: "verdict.json",
						schema_ref: "verdict.schema.json",
						required_fields: ["status", "model_name", "readiness", "validation", "artifacts"],
						gate: {
							validator_id: "python-script",
							backend_operation_id: "sure.trans.validate_verdict",
							script_id: "check_artifact.py",
							script_args: ["--kind", "verdict"],
						},
						owned_scripts: ["write_verdict.py"],
					},
					{
						id: "extract_lessons",
						label: "Extract lessons",
						kind: "gate",
						produces: "extraction_declaration.json",
						schema_ref: "extraction_declaration.schema.json",
						required_fields: [
							"schema",
							"no_new_lessons",
							"no_lessons_reason",
							"covered_by",
							"candidates",
							"infra_noise",
							"infra_evidence",
						],
						allowed_values: {
							schema: ["sure.memory.extraction.v2"],
						},
						gate: {
							validator_id: "python-script",
							backend_operation_id: "sure.memory.validate_extraction",
							script_id: "check_memory_extraction.py",
							gate_inputs: ["candidates", "memory_evidence"],
						},
						owned_scripts: ["build_run_digest.py"],
					},
					{
						id: "finalize_model_bundle",
						label: "Seal Eval-ready model bundle",
						kind: "gate",
						produces: "deployment_ready.json",
						schema_ref: "deployment_ready.schema.json",
						required_fields: [
							"schema",
							"status",
							"model_name",
							"package_profile",
							"execution_policy",
							"required_artifact_sha256",
							"bundle_identity_sha256",
						],
						gate: {
							validator_id: "python-script",
							backend_operation_id: "sure.trans.validate_finalized_bundle",
							script_id: "check_artifact.py",
							script_args: ["--kind", "deployment_ready"],
						},
						owned_scripts: ["finalize_trans_bundle.py"],
					},
				],
				initial_unit_id: "load_trans_input",
				terminal_unit_id: "finalize_model_bundle",
			},
		],
		default_branch_id: "main",
		retry_policy: {
			default_max_retries: 3,
			exempt_from_exhaustion: ["extract_lessons"],
		},
	},
	unit_outputs: [
		{
			type: "unit.load_trans_input",
			path: "artifacts/trans_input_resolved.json",
			required: true,
			description: "Output required before advancing from load_trans_input.",
			scope: "run-local",
			publication_mode: "run-local",
			owner: "validator",
		},
		{
			type: "unit.inspect_dependencies",
			path: "artifacts/inference_dependency_report.json",
			required: true,
			description: "Output required before advancing from inspect_dependencies.",
			scope: "run-local",
			publication_mode: "run-local",
			owner: "validator",
		},
		{
			type: "unit.detect_framework",
			path: "artifacts/framework_detection.json",
			required: true,
			description: "Output required before advancing from detect_framework.",
			scope: "run-local",
			publication_mode: "run-local",
			owner: "validator",
		},
		{
			type: "unit.prepare_fixture",
			path: "artifacts/fixture_manifest.json",
			required: true,
			description: "Output required before advancing from prepare_fixture.",
			scope: "run-local",
			publication_mode: "run-local",
			owner: "validator",
		},
		{
			type: "unit.build_source_image",
			path: "artifacts/source_image_result.json",
			required: true,
			description: "Output required before advancing from build_source_image.",
			scope: "run-local",
			publication_mode: "run-local",
			owner: "validator",
		},
		{
			type: "unit.validate_env_compat",
			path: "artifacts/execution_compat.json",
			required: true,
			description: "Output required before advancing from validate_env_compat.",
			scope: "run-local",
			publication_mode: "run-local",
			owner: "validator",
		},
		{
			type: "unit.validate_original_inference",
			path: "artifacts/original_inference_result.json",
			required: true,
			description: "Output required before advancing from validate_original_inference.",
			scope: "run-local",
			publication_mode: "run-local",
			owner: "validator",
		},
		{
			type: "unit.stage_model_payload",
			path: "artifacts/model_payload_manifest.json",
			required: true,
			description: "Output required before advancing from stage_model_payload.",
			scope: "run-local",
			publication_mode: "run-local",
			owner: "validator",
		},
		{
			type: "unit.generate_adapter",
			path: "artifacts/adapter_manifest.json",
			required: true,
			description: "Output required before advancing from generate_adapter.",
			scope: "run-local",
			publication_mode: "run-local",
			owner: "validator",
		},
		{
			type: "unit.build_adapter_image",
			path: "artifacts/adapter_image_result.json",
			required: true,
			description: "Output required before advancing from build_adapter_image.",
			scope: "run-local",
			publication_mode: "run-local",
			owner: "validator",
		},
		{
			type: "unit.validate_import",
			path: "artifacts/import_result.json",
			required: true,
			description: "Output required before advancing from validate_import.",
			scope: "run-local",
			publication_mode: "run-local",
			owner: "validator",
		},
		{
			type: "unit.validate_load",
			path: "artifacts/load_result.json",
			required: true,
			description: "Output required before advancing from validate_load.",
			scope: "run-local",
			publication_mode: "run-local",
			owner: "validator",
		},
		{
			type: "unit.validate_infer",
			path: "artifacts/infer_result.json",
			required: true,
			description: "Output required before advancing from validate_infer.",
			scope: "run-local",
			publication_mode: "run-local",
			owner: "validator",
		},
		{
			type: "unit.validate_contract",
			path: "artifacts/contract_result.json",
			required: true,
			description: "Output required before advancing from validate_contract.",
			scope: "run-local",
			publication_mode: "run-local",
			owner: "validator",
		},
		{
			type: "unit.validate_mcp",
			path: "artifacts/mcp_result.json",
			required: true,
			description: "Output required before advancing from validate_mcp.",
			scope: "run-local",
			publication_mode: "run-local",
			owner: "validator",
		},
		{
			type: "unit.validate_equivalence",
			path: "artifacts/equivalence_result.json",
			required: true,
			description: "Output required before advancing from validate_equivalence.",
			scope: "run-local",
			publication_mode: "run-local",
			owner: "validator",
		},
		{
			type: "unit.package_container",
			path: "artifacts/docker_registry_result.json",
			required: true,
			description: "Output required before advancing from package_container.",
			scope: "run-local",
			publication_mode: "run-local",
			owner: "validator",
		},
		{
			type: "unit.write_runtime_inventory",
			path: "artifacts/runtime_inventory.json",
			required: true,
			description: "Output required before advancing from write_runtime_inventory.",
			scope: "run-local",
			publication_mode: "run-local",
			owner: "validator",
		},
		{
			type: "unit.verdict",
			path: "artifacts/verdict.json",
			required: true,
			description: "Output required before advancing from verdict.",
			scope: "run-local",
			publication_mode: "run-local",
			owner: "validator",
		},
		{
			type: "unit.extract_lessons",
			path: "artifacts/extraction_declaration.json",
			required: true,
			description: "Output required before advancing from extract_lessons.",
			scope: "run-local",
			publication_mode: "run-local",
			owner: "validator",
		},
		{
			type: "unit.finalize_model_bundle",
			path: "artifacts/deployment_ready.json",
			required: true,
			description: "Output required before advancing from finalize_model_bundle.",
			scope: "run-local",
			publication_mode: "run-local",
			owner: "validator",
		},
	],
	internal_evidence: [
		{
			type: "checkpoint",
			path: "state.json",
			required: true,
			description: "Legacy-compatible checkpoint projection.",
			scope: "run-local",
			publication_mode: "run-local",
			owner: "harness",
		},
		{
			type: "event_log",
			path: "events.jsonl",
			required: true,
			description: "Append-only lifecycle and validator events.",
			scope: "run-local",
			publication_mode: "append-only",
			owner: "harness",
		},
	],
	published_artifacts: [
		{
			type: "dependency_report",
			path: "artifacts/inference_dependency_report.json",
			required: true,
			description: "Resolved static and dynamic inference dependency evidence.",
			scope: "run-local",
			publication_mode: "run-local",
			owner: "agent",
		},
		{
			type: "framework_detection",
			path: "artifacts/framework_detection.json",
			required: true,
			description: "Declared and detected computation/model framework evidence with architecture clarification.",
			scope: "run-local",
			publication_mode: "run-local",
			owner: "agent",
		},
		{
			type: "fixture",
			path: "artifacts/fixture_manifest.json",
			required: true,
			description: "Bounded real smoke fixture staged for original and adapter inference.",
			scope: "run-local",
			publication_mode: "run-local",
			owner: "agent",
		},
		{
			type: "execution_compat",
			path: "artifacts/execution_compat.json",
			required: true,
			description: "Source-runtime Python, framework, CUDA, and BF16 compatibility probe.",
			scope: "run-local",
			publication_mode: "run-local",
			owner: "executor",
		},
		{
			type: "source_runtime",
			path: "artifacts/source_image_result.json",
			required: true,
			description: "Verified Docker image or locked local Python source runtime evidence.",
			scope: "run-local",
			publication_mode: "run-local",
			owner: "executor",
		},
		{
			type: "model_payload",
			path: "artifacts/model_payload_manifest.json",
			required: true,
			description: "Materialized model payload manifest for the final approved bundle.",
			scope: "run-local",
			publication_mode: "run-local",
			owner: "agent",
		},
		{
			type: "runtime_inventory",
			path: "artifacts/runtime_inventory.json",
			required: true,
			description: "Container or sealed uv Model Runtime binding for Eval.",
			scope: "run-local",
			publication_mode: "run-local",
			owner: "executor",
		},
		{
			type: "verdict",
			path: "artifacts/verdict.json",
			required: true,
			description: "Original and adapter inference validation verdict.",
			scope: "run-local",
			publication_mode: "run-local",
			owner: "agent",
		},
		{
			type: "deployment_ready",
			path: "artifacts/deployment_ready.json",
			required: true,
			description: "Terminal integrity-pinned Eval readiness marker.",
			scope: "run-local",
			publication_mode: "run-local",
			owner: "agent",
		},
	],
	capabilities: [
		{
			capability_id: "sure.execution.harness-python",
			capability_class: "execution_capability",
			required: true,
			description: "Locked SURE Harness Python runtime for deterministic gates.",
		},
		{
			capability_id: "sure.execution.source-runtime",
			capability_class: "execution_capability",
			required: true,
			description: "Docker or locked Python source runtime selected by the request.",
		},
	],
	semantic_validators: [
		{
			id: "python-script",
			operation: "validate",
			script: "check_artifact.py",
			description: "Semantic validator python-script registered by the load_trans_input gate.",
		},
		{
			id: "legacy-in-process",
			operation: "validate",
			description: "Semantic validator legacy-in-process registered by the generate_adapter gate.",
		},
	],
	instructions: {
		common_path: "instructions.common.md",
		portable_path: "instructions.portable.md",
		pi_path: "instructions.pi.md",
	},
	resources: {
		directories: ["scripts", "schemas", "references", "examples"],
		legacy_root: "sure/skills/sure_trans",
	},
	pi: {
		name: "sure_trans",
		command: "/sure_trans",
		description:
			"Transform an existing Docker or locked Python model runtime, model path, and inference entrypoint into a SURE Eval deployment bundle.",
		prompt: "SKILL.md",
		hooks: {
			pre_start: [
				{
					module: "hooks/index.ts",
					handler: "preStart",
				},
			],
			pre_tool_call: [
				{
					module: "hooks/index.ts",
					handler: "preToolCall",
				},
			],
			post_tool_result: [
				{
					module: "hooks/index.ts",
					handler: "postToolResult",
				},
			],
			pre_finish: [
				{
					module: "hooks/index.ts",
					handler: "preFinish",
				},
			],
			post_finish: [
				{
					module: "hooks/index.ts",
					handler: "postFinish",
				},
			],
			on_error: [
				{
					module: "hooks/index.ts",
					handler: "onError",
				},
			],
		},
		ui: {
			primaryCounters: ["completed_units", "total_units", "gate_blocks"],
			artifactTypes: [
				"dependency_report",
				"framework_detection",
				"fixture",
				"execution_compat",
				"source_runtime",
				"model_payload",
				"runtime_inventory",
				"verdict",
				"deployment_ready",
			],
			defaultExpandedSections: ["diagnostics", "artifacts"],
		},
	},
});

export default SURE_TRANS_CANONICAL;
