import { defineCanonicalSkill } from "../../define.ts";
import type { CanonicalSkillDefinition } from "../../types.ts";

export const SURE_ONBOARD_CANONICAL: CanonicalSkillDefinition = defineCanonicalSkill({
	schema: "sure.canonical.skill.v1",
	skill_id: "sure_onboard",
	command_id: "sure-onboard",
	distribution_slug: "sure-onboard",
	display_name: "SURE Onboard",
	description: "Onboard or repair a model, validate its inference contract, and seal a reproducible Eval runtime.",
	workflow: {
		schema: "sure.workflow.definition.v1",
		workflow_id: "sure_onboard",
		version: "legacy-v1",
		checkpoint_id: "main_flow",
		checkpoint_label: "SURE model-tool state machine",
		branches: [
			{
				id: "main",
				units: [
					{
						id: "load_model_input",
						label: "Load MODEL_INPUT",
						kind: "gate",
						produces: "model_input_resolved.json",
						schema_ref: "model_input_resolved.schema.json",
						required_fields: [
							"model_id",
							"model_name",
							"model_dir",
							"repo_url",
							"deployment_type",
							"package_profile",
						],
						forbidden_fields: ["status", "wrapper_path"],
						allowed_values: {
							task_type: [
								"asr",
								"s2tt",
								"sd",
								"ser",
								"tts",
								"vc",
								"kws",
								"slu",
								"gr",
								"speech_understanding",
								"sa-asr",
								"sa_asr",
							],
							deployment_type: ["local", "api"],
							package_profile: ["none", "docker-local", "docker-registry"],
						},
						gate: {
							validator_id: "python-script",
							script_id: "check_model_input.py",
						},
						helper_scripts: ["materialize_onboard_inputs.py"],
					},
					{
						id: "context_selection",
						label: "Select context",
						kind: "linear",
						produces: "context_selection.json",
						schema_ref: "context_selection.schema.json",
						required_fields: ["task_type", "selected_references"],
						forbidden_fields: ["status", "wrapper_path"],
						allowed_values: {
							task_type: [
								"asr",
								"s2tt",
								"sd",
								"ser",
								"tts",
								"vc",
								"kws",
								"slu",
								"gr",
								"speech_understanding",
								"sa-asr",
								"sa_asr",
							],
						},
					},
					{
						id: "discover",
						label: "Discover repo",
						kind: "linear",
						produces: "repo_summary.json",
						schema_ref: "repo_summary.schema.json",
						required_fields: ["repo_url"],
						forbidden_fields: ["status", "wrapper_path"],
					},
					{
						id: "classify",
						label: "Classify model",
						kind: "linear",
						produces: "classification.json",
						schema_ref: "classification.schema.json",
						required_fields: ["task_type"],
						forbidden_fields: ["status", "wrapper_path"],
						allowed_values: {
							task_type: [
								"asr",
								"s2tt",
								"sd",
								"ser",
								"tts",
								"vc",
								"kws",
								"slu",
								"gr",
								"speech_understanding",
								"sa-asr",
								"sa_asr",
							],
						},
					},
					{
						id: "plan",
						label: "Select backend",
						kind: "linear",
						produces: "backend_choice.json",
						schema_ref: "backend_choice.schema.json",
						required_fields: ["backend"],
						forbidden_fields: ["status", "wrapper_path"],
						allowed_values: {
							backend: ["uv", "pip", "conda", "pixi", "docker", "api"],
						},
					},
					{
						id: "build_plan",
						label: "Build plan",
						kind: "gate",
						produces: "build_plan.json",
						schema_ref: "build_plan.schema.json",
						required_fields: ["model_id", "model_dir", "backend", "steps", "package_profile"],
						forbidden_fields: ["wrapper_path"],
						allowed_values: {
							backend: ["uv", "pip", "conda", "pixi", "docker", "api"],
							package_profile: ["none", "docker-local", "docker-registry"],
						},
						gate: {
							validator_id: "python-script",
							script_id: "check_build_plan.py",
						},
					},
					{
						id: "validate_spec",
						label: "Validate spec",
						kind: "gate",
						produces: "spec_validation.json",
						schema_ref: "spec_validation.schema.json",
						required_fields: ["checks", "status"],
						gate: {
							validator_id: "python-script",
							script_id: "check_spec.py",
						},
					},
					{
						id: "prepare_fixture",
						label: "Prepare fixture",
						kind: "gate",
						produces: "fixture_manifest.json",
						schema_ref: "fixture_manifest.schema.json",
						required_fields: ["model_dir", "task_type", "staged_dir", "gt_jsonl", "samples", "sample_count"],
						gate: {
							validator_id: "python-script",
							script_id: "check_fixture.py",
						},
						helper_scripts: ["prepare_fixture.py"],
					},
					{
						id: "build_env",
						label: "Build environment",
						kind: "gate",
						produces: "build_env_result.json",
						schema_ref: "build_env_result.schema.json",
						required_fields: ["env_ready"],
						gate: {
							validator_id: "python-script",
							script_id: "check_env.py",
						},
						helper_scripts: ["materialize_model_runtime.py"],
					},
					{
						id: "fetch_weights",
						label: "Fetch weights",
						kind: "gate",
						produces: "weights_manifest.json",
						schema_ref: "weights_manifest.schema.json",
						gate: {
							validator_id: "python-script",
							script_id: "check_weights.py",
						},
					},
					{
						id: "validate_env_compat",
						label: "Validate env compatibility",
						kind: "gate",
						produces: "env_compat_result.json",
						schema_ref: "env_compat_result.schema.json",
						required_fields: ["compat_ok"],
						gate: {
							validator_id: "python-script",
							script_id: "check_env_compat.py",
						},
					},
					{
						id: "generate_wrapper",
						label: "Generate wrapper",
						kind: "linear",
						produces: "wrapper_manifest.json",
						schema_ref: "wrapper_manifest.schema.json",
						required_fields: ["wrapper_path"],
						forbidden_fields: ["status"],
					},
					{
						id: "validate_import",
						label: "Validate import",
						kind: "gate",
						produces: "import_result.json",
						schema_ref: "import_result.schema.json",
						required_fields: ["import_passed"],
						gate: {
							validator_id: "python-script",
							script_id: "run_validate.py",
						},
					},
					{
						id: "validate_load",
						label: "Validate load",
						kind: "gate",
						produces: "load_result.json",
						schema_ref: "load_result.schema.json",
						required_fields: ["load_passed"],
						gate: {
							validator_id: "python-script",
							script_id: "run_validate.py",
						},
					},
					{
						id: "validate_infer",
						label: "Validate inference",
						kind: "gate",
						produces: "infer_result.json",
						schema_ref: "infer_result.schema.json",
						required_fields: ["infer_passed"],
						gate: {
							validator_id: "python-script",
							script_id: "run_validate.py",
						},
					},
					{
						id: "validate_contract",
						label: "Validate contract",
						kind: "gate",
						produces: "contract_result.json",
						schema_ref: "contract_result.schema.json",
						required_fields: ["contract_passed"],
						gate: {
							validator_id: "python-script",
							script_id: "run_validate.py",
						},
					},
					{
						id: "package_container",
						label: "Package container",
						kind: "gate",
						produces: "docker_registry_result.json",
						schema_ref: "docker_registry_result.schema.json",
						required_fields: ["schema", "status"],
						gate: {
							validator_id: "python-script",
							script_id: "check_container_package.py",
						},
						helper_scripts: ["describe_harness_runtime.py"],
					},
					{
						id: "save_artifacts",
						label: "Save artifacts",
						kind: "gate",
						produces: "artifact_manifest.json",
						schema_ref: "artifact_manifest.schema.json",
						gate: {
							validator_id: "python-script",
							script_id: "check_artifact_manifest.py",
						},
						helper_scripts: ["stage_model_artifacts.py"],
					},
					{
						id: "package_gate",
						label: "Package gate",
						kind: "gate",
						produces: "package_gate.json",
						schema_ref: "package_gate.schema.json",
						required_fields: ["status", "package_profile", "readiness"],
						allowed_values: {
							status: ["passed", "failed", "blocked", "skipped"],
							package_profile: ["none", "docker-local", "docker-registry"],
						},
						gate: {
							validator_id: "python-script",
							script_id: "check_package_gate.py",
						},
						helper_scripts: ["write_package_gate.py"],
					},
					{
						id: "write_runtime_inventory",
						label: "Write runtime inventory",
						kind: "gate",
						produces: "runtime_inventory.json",
						schema_ref: "runtime_inventory.schema.json",
						required_fields: ["schema", "status", "model", "local_runtime", "container_runtime", "policy"],
						gate: {
							validator_id: "python-script",
							script_id: "check_runtime_inventory.py",
						},
						helper_scripts: ["write_runtime_inventory.py"],
					},
					{
						id: "verdict",
						label: "Verdict",
						kind: "gate",
						produces: "verdict.json",
						schema_ref: "verdict.schema.json",
						required_fields: ["status"],
						gate: {
							validator_id: "python-script",
							script_id: "check_verdict.py",
						},
						helper_scripts: ["write_verdict.py"],
					},
					{
						id: "extract_lessons",
						label: "Extract lessons",
						kind: "gate",
						produces: "extraction_declaration.json",
						schema_ref: "extraction_declaration.schema.json",
						required_fields: [
							"schema",
							"no_new_lessons",
							"no_lessons_reason",
							"covered_by",
							"candidates",
							"infra_noise",
							"infra_evidence",
						],
						allowed_values: {
							schema: ["sure.memory.extraction.v2"],
						},
						gate: {
							validator_id: "python-script",
							script_id: "check_memory_extraction.py",
							gate_inputs: ["candidates", "memory_evidence"],
						},
						helper_scripts: ["build_run_digest.py"],
					},
					{
						id: "finalize_model_bundle",
						label: "Finalize model bundle",
						kind: "gate",
						produces: "deployment_ready.json",
						schema_ref: "deployment_ready_output.schema.json",
						required_fields: ["schema", "status", "model_name", "package_profile", "execution_policy"],
						gate: {
							validator_id: "python-script",
							script_id: "check_finalized_bundle.py",
						},
						helper_scripts: ["finalize_model_bundle.py"],
					},
				],
				initial_unit_id: "load_model_input",
				terminal_unit_id: "finalize_model_bundle",
			},
		],
		default_branch_id: "main",
		retry_policy: {
			default_max_retries: 3,
			exempt_from_exhaustion: ["extract_lessons"],
		},
	},
	unit_outputs: [
		{
			type: "unit.load_model_input",
			path: "artifacts/model_input_resolved.json",
			required: true,
			description: "Output required before advancing from load_model_input.",
			scope: "run-local",
			publication_mode: "run-local",
			owner: "validator",
		},
		{
			type: "unit.context_selection",
			path: "artifacts/context_selection.json",
			required: true,
			description: "Output required before advancing from context_selection.",
			scope: "run-local",
			publication_mode: "run-local",
			owner: "agent",
		},
		{
			type: "unit.discover",
			path: "artifacts/repo_summary.json",
			required: true,
			description: "Output required before advancing from discover.",
			scope: "run-local",
			publication_mode: "run-local",
			owner: "agent",
		},
		{
			type: "unit.classify",
			path: "artifacts/classification.json",
			required: true,
			description: "Output required before advancing from classify.",
			scope: "run-local",
			publication_mode: "run-local",
			owner: "agent",
		},
		{
			type: "unit.plan",
			path: "artifacts/backend_choice.json",
			required: true,
			description: "Output required before advancing from plan.",
			scope: "run-local",
			publication_mode: "run-local",
			owner: "agent",
		},
		{
			type: "unit.build_plan",
			path: "artifacts/build_plan.json",
			required: true,
			description: "Output required before advancing from build_plan.",
			scope: "run-local",
			publication_mode: "run-local",
			owner: "validator",
		},
		{
			type: "unit.validate_spec",
			path: "artifacts/spec_validation.json",
			required: true,
			description: "Output required before advancing from validate_spec.",
			scope: "run-local",
			publication_mode: "run-local",
			owner: "validator",
		},
		{
			type: "unit.prepare_fixture",
			path: "artifacts/fixture_manifest.json",
			required: true,
			description: "Output required before advancing from prepare_fixture.",
			scope: "run-local",
			publication_mode: "run-local",
			owner: "validator",
		},
		{
			type: "unit.build_env",
			path: "artifacts/build_env_result.json",
			required: true,
			description: "Output required before advancing from build_env.",
			scope: "run-local",
			publication_mode: "run-local",
			owner: "validator",
		},
		{
			type: "unit.fetch_weights",
			path: "artifacts/weights_manifest.json",
			required: true,
			description: "Output required before advancing from fetch_weights.",
			scope: "run-local",
			publication_mode: "run-local",
			owner: "validator",
		},
		{
			type: "unit.validate_env_compat",
			path: "artifacts/env_compat_result.json",
			required: true,
			description: "Output required before advancing from validate_env_compat.",
			scope: "run-local",
			publication_mode: "run-local",
			owner: "validator",
		},
		{
			type: "unit.generate_wrapper",
			path: "artifacts/wrapper_manifest.json",
			required: true,
			description: "Output required before advancing from generate_wrapper.",
			scope: "run-local",
			publication_mode: "run-local",
			owner: "agent",
		},
		{
			type: "unit.validate_import",
			path: "artifacts/import_result.json",
			required: true,
			description: "Output required before advancing from validate_import.",
			scope: "run-local",
			publication_mode: "run-local",
			owner: "validator",
		},
		{
			type: "unit.validate_load",
			path: "artifacts/load_result.json",
			required: true,
			description: "Output required before advancing from validate_load.",
			scope: "run-local",
			publication_mode: "run-local",
			owner: "validator",
		},
		{
			type: "unit.validate_infer",
			path: "artifacts/infer_result.json",
			required: true,
			description: "Output required before advancing from validate_infer.",
			scope: "run-local",
			publication_mode: "run-local",
			owner: "validator",
		},
		{
			type: "unit.validate_contract",
			path: "artifacts/contract_result.json",
			required: true,
			description: "Output required before advancing from validate_contract.",
			scope: "run-local",
			publication_mode: "run-local",
			owner: "validator",
		},
		{
			type: "unit.package_container",
			path: "artifacts/docker_registry_result.json",
			required: true,
			description: "Output required before advancing from package_container.",
			scope: "run-local",
			publication_mode: "run-local",
			owner: "validator",
		},
		{
			type: "unit.save_artifacts",
			path: "artifacts/artifact_manifest.json",
			required: true,
			description: "Output required before advancing from save_artifacts.",
			scope: "run-local",
			publication_mode: "run-local",
			owner: "validator",
		},
		{
			type: "unit.package_gate",
			path: "artifacts/package_gate.json",
			required: true,
			description: "Output required before advancing from package_gate.",
			scope: "run-local",
			publication_mode: "run-local",
			owner: "validator",
		},
		{
			type: "unit.write_runtime_inventory",
			path: "artifacts/runtime_inventory.json",
			required: true,
			description: "Output required before advancing from write_runtime_inventory.",
			scope: "run-local",
			publication_mode: "run-local",
			owner: "validator",
		},
		{
			type: "unit.verdict",
			path: "artifacts/verdict.json",
			required: true,
			description: "Output required before advancing from verdict.",
			scope: "run-local",
			publication_mode: "run-local",
			owner: "validator",
		},
		{
			type: "unit.extract_lessons",
			path: "artifacts/extraction_declaration.json",
			required: true,
			description: "Output required before advancing from extract_lessons.",
			scope: "run-local",
			publication_mode: "run-local",
			owner: "validator",
		},
		{
			type: "unit.finalize_model_bundle",
			path: "artifacts/deployment_ready.json",
			required: true,
			description: "Output required before advancing from finalize_model_bundle.",
			scope: "run-local",
			publication_mode: "run-local",
			owner: "validator",
		},
	],
	internal_evidence: [
		{
			type: "checkpoint",
			path: "state.json",
			required: true,
			description: "Legacy-compatible checkpoint projection.",
			scope: "run-local",
			publication_mode: "run-local",
			owner: "harness",
		},
		{
			type: "event_log",
			path: "events.jsonl",
			required: true,
			description: "Append-only lifecycle and validator events.",
			scope: "run-local",
			publication_mode: "append-only",
			owner: "harness",
		},
	],
	published_artifacts: [
		{
			type: "verdict",
			path: "artifacts/verdict.json",
			required: true,
			description: "Final SURE-EVAL model-tool verdict (verdict.json).",
			scope: "run-local",
			publication_mode: "run-local",
			owner: "agent",
		},
		{
			type: "model_spec",
			required: false,
			description: "Model specification (model.spec.yaml).",
			scope: "workspace-global",
			publication_mode: "workspace-global",
			owner: "agent",
		},
		{
			type: "wrapper",
			required: false,
			description: "Generated wrapper file set (model.py, server.py, __init__.py, validate.py).",
			scope: "workspace-global",
			publication_mode: "workspace-global",
			owner: "agent",
		},
		{
			type: "build_plan",
			path: "artifacts/build_plan.json",
			required: false,
			description: "Executable onboarding build plan.",
			scope: "run-local",
			publication_mode: "run-local",
			owner: "agent",
		},
		{
			type: "fixture_manifest",
			path: "artifacts/fixture_manifest.json",
			required: false,
			description: "Prepared model-local fixture manifest.",
			scope: "run-local",
			publication_mode: "run-local",
			owner: "agent",
		},
		{
			type: "package_gate",
			path: "artifacts/package_gate.json",
			required: false,
			description: "Selected package profile readiness gate result.",
			scope: "run-local",
			publication_mode: "run-local",
			owner: "agent",
		},
		{
			type: "runtime_inventory",
			path: "artifacts/runtime_inventory.json",
			required: true,
			description: "Sealed container or local Python Eval runtime binding.",
			scope: "run-local",
			publication_mode: "run-local",
			owner: "executor",
		},
		{
			type: "deployment_ready",
			path: "artifacts/deployment_ready.json",
			required: true,
			description: "Terminal portable bundle and approved runtime readiness marker.",
			scope: "run-local",
			publication_mode: "run-local",
			owner: "agent",
		},
	],
	capabilities: [
		{
			capability_id: "sure.execution.harness-python",
			capability_class: "execution_capability",
			required: true,
			description: "Locked SURE Harness Python runtime for deterministic gates.",
		},
		{
			capability_id: "sure.execution.docker-optional",
			capability_class: "execution_capability",
			required: false,
			description: "Docker is required only for container package profiles.",
		},
	],
	semantic_validators: [
		{
			id: "python-script",
			operation: "validate",
			script: "check_model_input.py",
			description: "Semantic validator python-script registered by the load_model_input gate.",
		},
	],
	instructions: {
		common_path: "instructions.common.md",
		portable_path: "instructions.portable.md",
		pi_path: "instructions.pi.md",
	},
	resources: {
		directories: ["scripts", "schemas", "references", "examples"],
		legacy_root: "sure/skills/sure_onboard",
	},
	pi: {
		name: "sure_onboard",
		command: "/sure_onboard",
		description:
			"Onboard or repair a model, validate its inference contract, and seal either a digest-pinned container or a site-approved local Python Eval binding.",
		prompt: "SKILL.md",
		hooks: {
			pre_start: [
				{
					module: "hooks/index.ts",
					handler: "preStart",
				},
			],
			pre_tool_call: [
				{
					module: "hooks/index.ts",
					handler: "preToolCall",
				},
			],
			post_tool_result: [
				{
					module: "hooks/index.ts",
					handler: "postToolResult",
				},
			],
			pre_finish: [
				{
					module: "hooks/index.ts",
					handler: "preFinish",
				},
			],
			post_finish: [
				{
					module: "hooks/index.ts",
					handler: "postFinish",
				},
			],
			on_error: [
				{
					module: "hooks/index.ts",
					handler: "onError",
				},
			],
		},
		ui: {
			primaryCounters: ["completed_units", "total_units", "gate_blocks"],
			artifactTypes: [
				"verdict",
				"deployment_ready",
				"runtime_inventory",
				"model_spec",
				"wrapper",
				"build_plan",
				"fixture_manifest",
				"package_gate",
				"artifact_manifest",
			],
			defaultExpandedSections: ["diagnostics", "artifacts"],
		},
	},
});

export default SURE_ONBOARD_CANONICAL;
