import { createHash } from "node:crypto";
import { existsSync, lstatSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";
import { canonicalJson, canonicalJsonDigest, sha256Hex } from "../packages/sure-core/src/contracts/canonical-json.ts";
import type { JsonValue } from "../packages/sure-core/src/contracts/types.ts";
import { executorRegistrySnapshot } from "../packages/sure-core/src/execution/registry.ts";
import { ValidatorRegistry, type ValidatorRegistrySnapshot } from "../packages/sure-core/src/validation/index.ts";
import { CANONICAL_SEMANTIC_BACKENDS } from "../sure/canonical/shared/evaluation/registry.ts";
import { CANONICAL_MEMORY_CONTRACT } from "../sure/canonical/shared/memory-contract.ts";
import { CANONICAL_SKILLS } from "../sure/canonical/skills/index.ts";
import type { CanonicalSkillDefinition } from "../sure/canonical/types.ts";
import { canonicalValidatorRegistry } from "../sure/canonical/validators/index.ts";

const repositoryRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const canonicalSkillsRoot = join(repositoryRoot, "sure", "canonical", "skills");
const generatedPiRoot = join(repositoryRoot, "sure", "generated", "pi", "skills");
const portableRoot = join(repositoryRoot, "sure", "dist", "agent-skills");
const portableRuntimeRoot = join(repositoryRoot, "sure", "dist", "portable-runtime");
const codingAgentWorkflowRegistry = join(
	repositoryRoot,
	"packages",
	"coding-agent",
	"src",
	"core",
	"sure",
	"generated-workflows.ts",
);
const GENERATED_MARKER = ".sure-generated";
const UNSAFE_PORTABLE_TEXT =
	/@earendil-works\/pi-coding-agent|HARNESS_PYTHON_BIN|sure_finish|sure_update_state|pre_start|pre_tool_call|post_tool_result|\.\.\/sure_[a-z_]+|sure\/skills\/sure_/;
const PORTABLE_RUNTIME_SUPPORT_FILES = [
	"sure/runtime/semantic_backend.py",
	"sure/runtime/resource_locator.py",
	"sure/runtime/repository_layout.py",
	"sure/runtime/execution_bridge.py",
	"sure/runtime/evaluation_commit.py",
	"sure/runtime/model/__init__.py",
	"sure/runtime/model/bootstrap.py",
	"sure/runtime/evaluation/requirements.in",
	"sure/runtime/evaluation/requirements.lock.txt",
	"sure/runtime/evaluation/runtime.json",
	"sure/runtime/harness/bootstrap.py",
	"sure/runtime/harness/build_image.py",
	"sure/runtime/harness/model_child_env.py",
	"sure/runtime/harness/Dockerfile",
	"sure/runtime/harness/requirements.in",
	"sure/runtime/harness/requirements.lock.txt",
	"sure/runtime/harness/runtime.json",
	"sure/site/container_delivery.py",
	"sure/site/loader.py",
	"sure/site/policy.schema.json",
] as const;

interface GeneratedFile {
	path: string;
	content: Buffer;
}

function asJson(value: unknown): JsonValue {
	return value as JsonValue;
}

function jsonFile(value: unknown): Buffer {
	return Buffer.from(`${canonicalJson(asJson(value))}\n`, "utf8");
}

function singleQuotedString(value: string): string {
	return `'${value
		.replace(/\\/g, "\\\\")
		.replace(/'/g, "\\'")
		.replace(/\u2028/g, "\\u2028")
		.replace(/\u2029/g, "\\u2029")}'`;
}

function workflowRegistryModule(): Buffer {
	const ids = CANONICAL_SKILLS.map((skill) => skill.skill_id);
	const workflows = Object.fromEntries(CANONICAL_SKILLS.map((skill) => [skill.skill_id, skill.workflow]));
	const serialized = canonicalJson(asJson(workflows));
	const chunks = Array.from({ length: Math.ceil(serialized.length / 100) }, (_, index) =>
		serialized.slice(index * 100, (index + 1) * 100),
	);
	return Buffer.from(
		[
			"// Generated by scripts/generate-sure-skills.ts. Do not edit.",
			'import type { WorkflowDefinition } from "@earendil-works/sure-core";',
			"",
			"export const SURE_WORKFLOW_IDS = [",
			...ids.map((id) => `\t${JSON.stringify(id)},`),
			"] as const;",
			"export type SureWorkflowId = (typeof SURE_WORKFLOW_IDS)[number];",
			"const SURE_WORKFLOW_JSON = [",
			...chunks.map((chunk) => `\t${singleQuotedString(chunk)},`),
			'].join("");',
			"export const SURE_WORKFLOWS = JSON.parse(SURE_WORKFLOW_JSON) as Readonly<Record<SureWorkflowId, WorkflowDefinition>>;",
			"const SURE_WORKFLOW_ID_SET = new Set<string>(SURE_WORKFLOW_IDS);",
			"",
			"export function isSureWorkflowId(value: string): value is SureWorkflowId {",
			"\treturn SURE_WORKFLOW_ID_SET.has(value);",
			"}",
			"",
			"export function workflowDefinitionForSkill(skillId: SureWorkflowId): WorkflowDefinition {",
			"\treturn SURE_WORKFLOWS[skillId];",
			"}",
			"",
		].join("\n"),
		"utf8",
	);
}

function sha256(value: Uint8Array): string {
	return createHash("sha256").update(value).digest("hex");
}

function materializedValidatorRegistry(): ValidatorRegistrySnapshot {
	const descriptors = canonicalValidatorRegistry()
		.list()
		.map((descriptor) => {
			if (descriptor.resource_path === undefined) return descriptor;
			const path = join(canonicalSkillsRoot, descriptor.resource_path);
			if (!existsSync(path) || !lstatSync(path).isFile()) {
				throw new Error(`Canonical validator resource is missing: ${descriptor.id} -> ${path}`);
			}
			return { ...descriptor, resource_digest: `sha256:${sha256(readFileSync(path))}` };
		});
	return new ValidatorRegistry(descriptors).snapshot();
}

function allFiles(root: string, prefix = ""): string[] {
	if (!existsSync(root)) return [];
	const entries = readdirSync(root, { withFileTypes: true }).sort((left, right) =>
		left.name.localeCompare(right.name),
	);
	const files: string[] = [];
	for (const entry of entries) {
		const relativePath = prefix ? `${prefix}/${entry.name}` : entry.name;
		const absolutePath = join(root, entry.name);
		if (entry.isDirectory()) {
			if (entry.name === "__pycache__" || entry.name === "node_modules") continue;
			files.push(...allFiles(absolutePath, relativePath));
		} else if (entry.isFile()) {
			if (
				entry.name.endsWith(".pyc") ||
				entry.name.endsWith(".js") ||
				entry.name.endsWith(".d.ts") ||
				entry.name.endsWith(".map")
			)
				continue;
			files.push(relativePath);
		}
	}
	return files;
}

function fileDigest(entries: readonly { path: string; content: Uint8Array }[]): string {
	const digestInput = [...entries]
		.sort((left, right) => left.path.localeCompare(right.path))
		.map((entry) => `${entry.path}\0${sha256(entry.content)}`)
		.join("\n");
	return sha256Hex(digestInput);
}

/** Hash a complete backend tree with the same path/content ordering on every host. */
function backendTreeDigest(root: string): string {
	const paths = allFiles(root).sort((left, right) => (left < right ? -1 : left > right ? 1 : 0));
	const rows = paths.map((path) => `${path}\0sha256:${sha256(readFileSync(join(root, path)))}`).join("\n");
	return `sha256:${sha256Hex(rows)}`;
}

interface MaterializedSemanticBackendManifest {
	schema: "sure.semantic.backend.manifest.v1";
	registry_digest: string;
	bundles: JsonValue[];
}

interface PortableRuntimeLock {
	schema: "sure.portable.runtime.lock.v1";
	runtime_version: "portable-v1";
	core_package_version: string;
	semantic_backend_registry_digest: string;
	executor_registry_digest: string;
	operation_ids: string[];
	files: Array<{ path: string; size_bytes: number; sha256: string }>;
	runtime_digest: string;
}

function materializedSemanticBackendManifest(): MaterializedSemanticBackendManifest {
	const bundles = CANONICAL_SEMANTIC_BACKENDS.map((bundle) => {
		const canonicalRoot = join(canonicalSkillsRoot, bundle.canonical_root);
		const legacyRoot = join(repositoryRoot, "sure", bundle.legacy_root);
		const canonicalIntegrityRoot = join(canonicalRoot, bundle.integrity_root);
		const legacyIntegrityRoot = join(legacyRoot, bundle.integrity_root);
		const canonicalTree = existsSync(canonicalIntegrityRoot) ? backendTreeDigest(canonicalIntegrityRoot) : undefined;
		const legacyTree = existsSync(legacyIntegrityRoot) ? backendTreeDigest(legacyIntegrityRoot) : undefined;
		const operations = bundle.operations.map((operation) => {
			const canonicalPath = join(canonicalRoot, operation.entrypoint);
			const legacyPath = join(legacyRoot, operation.entrypoint);
			if (!existsSync(canonicalPath) || !lstatSync(canonicalPath).isFile()) {
				throw new Error(
					`Canonical semantic backend resource is missing: ${operation.operation_id} -> ${canonicalPath}`,
				);
			}
			if (!existsSync(legacyPath) || !lstatSync(legacyPath).isFile()) {
				throw new Error(`Legacy semantic backend resource is missing: ${operation.operation_id} -> ${legacyPath}`);
			}
			return {
				...operation,
				canonical_resource_digest: `sha256:${sha256(readFileSync(canonicalPath))}`,
				legacy_resource_digest: `sha256:${sha256(readFileSync(legacyPath))}`,
			};
		});
		return {
			...bundle,
			canonical_tree_digest: canonicalTree,
			legacy_tree_digest: legacyTree,
			operations,
		};
	});
	const unsigned = { schema: "sure.semantic.backend.manifest.v1", bundles } as unknown as JsonValue;
	return {
		schema: "sure.semantic.backend.manifest.v1",
		registry_digest: canonicalJsonDigest(unsigned),
		bundles: bundles as unknown as JsonValue[],
	};
}

function portableRuntimeFiles(semanticBackendManifest: MaterializedSemanticBackendManifest): {
	files: GeneratedFile[];
	lock: PortableRuntimeLock;
} {
	const files: GeneratedFile[] = [
		{ path: join(portableRuntimeRoot, "semantic-backends.json"), content: jsonFile(semanticBackendManifest) },
		{ path: join(portableRuntimeRoot, "executor-registry.json"), content: jsonFile(executorRegistrySnapshot()) },
		{
			path: join(portableRuntimeRoot, "contracts", "portable_runtime_lock.schema.json"),
			content: readFileSync(join(repositoryRoot, "sure", "core", "contracts", "portable_runtime_lock.schema.json")),
		},
	];
	for (const path of ["sure/__init__.py", "sure/runtime/__init__.py", "sure/site/__init__.py"]) {
		files.push({
			path: join(portableRuntimeRoot, path),
			content: Buffer.from('"""Generated SURE portable runtime package."""\n', "utf8"),
		});
	}
	for (const sourcePath of PORTABLE_RUNTIME_SUPPORT_FILES) {
		const source = join(repositoryRoot, sourcePath);
		if (!existsSync(source) || !lstatSync(source).isFile()) {
			throw new Error(`Portable runtime support file is missing: ${source}`);
		}
		files.push({ path: join(portableRuntimeRoot, sourcePath), content: readFileSync(source) });
	}
	for (const rawBundle of semanticBackendManifest.bundles) {
		const bundle = rawBundle as Record<string, JsonValue>;
		const bundleId = String(bundle.bundle_id);
		const canonicalRoot = String(bundle.canonical_root);
		const integrityRoot = String(bundle.integrity_root ?? ".");
		const sourceRoot = join(canonicalSkillsRoot, canonicalRoot, integrityRoot);
		if (!existsSync(sourceRoot) || !lstatSync(sourceRoot).isDirectory()) {
			throw new Error(`Portable semantic backend root is missing: ${bundleId} -> ${sourceRoot}`);
		}
		for (const path of allFiles(sourceRoot)) {
			files.push({
				path: join(portableRuntimeRoot, "backends", bundleId, integrityRoot, path),
				content: readFileSync(join(sourceRoot, path)),
			});
		}
	}
	const generatedPaths = files.map((file) => relative(portableRuntimeRoot, file.path).replaceAll("\\", "/"));
	if (new Set(generatedPaths).size !== generatedPaths.length) {
		throw new Error("Portable runtime contains duplicate generated paths");
	}
	const fileEntries = files
		.map((file) => ({
			path: relative(portableRuntimeRoot, file.path).replaceAll("\\", "/"),
			size_bytes: file.content.byteLength,
			sha256: `sha256:${sha256(file.content)}`,
		}))
		.sort((left, right) => left.path.localeCompare(right.path));
	const unsigned = {
		schema: "sure.portable.runtime.lock.v1" as const,
		runtime_version: "portable-v1" as const,
		core_package_version: "0.80.3",
		semantic_backend_registry_digest: semanticBackendManifest.registry_digest,
		executor_registry_digest: executorRegistrySnapshot().registry_digest,
		operation_ids: semanticBackendManifest.bundles
			.flatMap((rawBundle) => {
				const bundle = rawBundle as Record<string, JsonValue>;
				return (bundle.operations as Array<Record<string, JsonValue>>).map((operation) =>
					String(operation.operation_id),
				);
			})
			.sort(),
		files: fileEntries,
	};
	const lock: PortableRuntimeLock = { ...unsigned, runtime_digest: canonicalJsonDigest(asJson(unsigned)) };
	files.push({ path: join(portableRuntimeRoot, "runtime-support.lock.json"), content: jsonFile(lock) });
	return { files, lock };
}

function readCanonicalResourceFiles(skill: CanonicalSkillDefinition): { path: string; content: Buffer }[] {
	const root = join(canonicalSkillsRoot, skill.distribution_slug);
	const files: { path: string; content: Buffer }[] = [];
	for (const directory of skill.resources.directories) {
		for (const path of allFiles(join(root, directory), directory)) {
			files.push({ path, content: readFileSync(join(root, path)) });
		}
	}
	return files;
}

function portableResourceFiles(skill: CanonicalSkillDefinition): {
	files: { path: string; content: Buffer }[];
	omitted: string[];
} {
	const selected: { path: string; content: Buffer }[] = [];
	const omitted: string[] = [];
	for (const entry of readCanonicalResourceFiles(skill)) {
		if (entry.path.startsWith("scripts/")) {
			omitted.push(entry.path);
			continue;
		}
		const text = entry.content.toString("utf8");
		if (UNSAFE_PORTABLE_TEXT.test(text)) {
			omitted.push(entry.path);
			continue;
		}
		selected.push(entry);
	}
	return { files: selected, omitted };
}

function workflowTable(skill: CanonicalSkillDefinition): string {
	return skill.workflow.branches
		.map(
			(branch) =>
				`### Branch ${branch.id}\n\n${branch.units
					.map((unit, index) => `${index + 1}. \`${unit.id}\` -> \`${unit.produces}\` (${unit.kind}).`)
					.join("\n")}`,
		)
		.join("\n\n");
}

function artifactTable(skill: CanonicalSkillDefinition): string {
	const rows = skill.published_artifacts.map(
		(artifact) =>
			`| \`${artifact.type}\` | ${artifact.path ? `\`${artifact.path}\`` : "(declared by producer)"} | ${artifact.required ? "yes" : "no"} |`,
	);
	return ["| Artifact | Path | Required |", "| --- | --- | --- |", ...rows].join("\n");
}

function portableSkillMarkdown(skill: CanonicalSkillDefinition): string {
	return [
		"---",
		`name: ${skill.distribution_slug}`,
		`description: ${JSON.stringify(skill.description)}`,
		"---",
		"",
		`# ${skill.display_name}`,
		"",
		`This portable skill coordinates ${skill.description.toLowerCase()}`,
		"",
		readFileSync(join(canonicalSkillsRoot, skill.distribution_slug, skill.instructions.common_path), "utf8").trim(),
		"",
		readFileSync(join(canonicalSkillsRoot, skill.distribution_slug, skill.instructions.portable_path), "utf8").trim(),
		"",
		"## Workflow reference",
		"",
		workflowTable(skill),
		"",
		"## Canonical artifact contract",
		"",
		artifactTable(skill),
		"",
		"## References",
		"",
		"Use only the bundled schemas and references that are present in this distribution. Semantic validators and execution are resolved by SURE Core from the pinned backend manifest; an agent must not substitute an unregistered checker.",
		"",
	].join("\n");
}

function yamlString(value: string): string {
	return JSON.stringify(value);
}

function openAiYaml(skill: CanonicalSkillDefinition): string {
	const display = skill.display_name;
	const short = `${skill.display_name.replace(/^SURE /, "")} workflow for reproducible model evaluation`;
	const prompt = `Use $${skill.distribution_slug} to ${skill.description.toLowerCase()}`;
	return [
		"interface:",
		`  display_name: ${yamlString(display)}`,
		`  short_description: ${yamlString(short.slice(0, 64))}`,
		`  default_prompt: ${yamlString(prompt)}`,
		"policy:",
		"  allow_implicit_invocation: true",
		"",
	].join("\n");
}

function portableMemoryReadme(skill: CanonicalSkillDefinition): string {
	return [
		"# SURE memory boundary",
		"",
		"This distribution carries the host-neutral `memory-contract.json` used by SURE Core.",
		"Memory is advisory: its diagnostics and references never manufacture a workflow PASS or change the business validator result.",
		"",
		"Validate the projection before using a host memory backend:",
		"",
		`\`surectl memory --contract ./memory-contract.json --skill ${skill.skill_id}\``,
		"",
		"Logical references use `memory://<skill>/<kind>/<slug>`. A backend that is not installed or cannot provide a structured receipt must be reported as `NOT_EXECUTED/CAPABILITY_MISSING`; it must not be substituted with a successful result.",
		"",
		"The portable package does not import Pi lifecycle modules. A host may provide the memory writer and its roots explicitly, while SURE Core remains authoritative for workflow transitions.",
		"",
	].join("\n");
}

function piManifest(skill: CanonicalSkillDefinition): Record<string, unknown> {
	return {
		name: skill.pi.name,
		command: skill.pi.command,
		description: skill.pi.description,
		prompt: skill.pi.prompt,
		hooks: skill.pi.hooks,
		artifacts: skill.published_artifacts.map(({ type, path, required, description }) => ({
			type,
			...(path === undefined ? {} : { path }),
			required,
			description,
		})),
		ui: skill.pi.ui,
	};
}

function sanitizePortableText(value: string): string {
	return value
		.replaceAll(/\/sure_[a-z_]+/g, "SURE workflow")
		.replaceAll("HARNESS_PYTHON_BIN", "the pinned harness runtime")
		.replaceAll("@earendil-works/pi-coding-agent", "the host adapter");
}

function portableDefinition(skill: CanonicalSkillDefinition): Record<string, unknown> {
	return {
		schema: skill.schema,
		skill_id: skill.skill_id,
		command_id: skill.command_id,
		distribution_slug: skill.distribution_slug,
		display_name: skill.display_name,
		description: sanitizePortableText(skill.description),
		workflow: skill.workflow,
		unit_outputs: skill.unit_outputs,
		internal_evidence: skill.internal_evidence,
		published_artifacts: skill.published_artifacts.map((artifact) => ({
			...artifact,
			description: sanitizePortableText(artifact.description),
		})),
		capabilities: skill.capabilities,
		semantic_validators: skill.semantic_validators,
		instructions: {
			common_path: skill.instructions.common_path,
			portable_path: skill.instructions.portable_path,
		},
		resources: { directories: skill.resources.directories },
	};
}

function lockFor(
	skill: CanonicalSkillDefinition,
	host: "pi" | "portable",
	resources: readonly { path: string; content: Uint8Array }[],
	omitted: readonly string[],
	semanticBackendManifest: MaterializedSemanticBackendManifest,
	memoryContract: Record<string, unknown>,
	semanticRuntimeDigest: string,
): Record<string, unknown> {
	const definitionDigest = canonicalJsonDigest(asJson(skill));
	const workflowDigest = canonicalJsonDigest(asJson(skill.workflow));
	const resourceDigest = fileDigest(resources);
	const backendDigest = fileDigest(
		readCanonicalResourceFiles(skill).filter((entry) => entry.path.startsWith("scripts/")),
	);
	const validatorRegistryDigest = materializedValidatorRegistry().digest;
	return {
		schema: "sure.skill.generation.lock.v1",
		host,
		skill_id: skill.skill_id,
		command_id: skill.command_id,
		distribution_slug: skill.distribution_slug,
		definition_digest: definitionDigest,
		workflow_digest: workflowDigest,
		resource_digest: resourceDigest,
		semantic_backend_digest: backendDigest,
		validator_registry_digest: validatorRegistryDigest,
		semantic_backend_registry_digest: semanticBackendManifest.registry_digest,
		semantic_runtime_digest: semanticRuntimeDigest,
		executor_registry_digest: executorRegistrySnapshot().registry_digest,
		memory_contract_digest: canonicalJsonDigest(asJson(memoryContract)),
		core_package_version: "0.80.3",
		portable_omitted_resources: [...omitted].sort(),
	};
}

function memoryContractFor(skill: CanonicalSkillDefinition): Record<string, unknown> {
	const enabled = skill.skill_id !== "sure_approve";
	return {
		...CANONICAL_MEMORY_CONTRACT,
		skill: {
			skill_id: skill.skill_id,
			enabled,
			participates_in_checkpoint: enabled,
		},
	};
}

function hookFacade(skill: CanonicalSkillDefinition): Buffer {
	const oldRoot = skill.resources.legacy_root ?? `sure/skills/${skill.skill_id}`;
	const generatedHooks = join(generatedPiRoot, skill.skill_id, "hooks");
	const oldHooks = join(repositoryRoot, oldRoot, "hooks");
	const relativeOld = relative(generatedHooks, oldHooks).replaceAll("\\", "/");
	const importPath = `${relativeOld || "."}/index.ts`;
	return Buffer.from(
		`// Generated Pi compatibility facade. Lifecycle authority remains the Pi adapter.\nexport * from ${JSON.stringify(importPath)};\n`,
		"utf8",
	);
}

function buildHostFiles(
	skill: CanonicalSkillDefinition,
	host: "pi" | "portable",
	semanticBackendManifest: MaterializedSemanticBackendManifest,
	semanticRuntimeDigest: string,
): { files: GeneratedFile[]; lock: Record<string, unknown> } {
	const canonicalRoot = join(canonicalSkillsRoot, skill.distribution_slug);
	const resourceSet =
		host === "portable"
			? portableResourceFiles(skill)
			: { files: readCanonicalResourceFiles(skill), omitted: [] as string[] };
	const root = host === "pi" ? join(generatedPiRoot, skill.skill_id) : join(portableRoot, skill.distribution_slug);
	const files: GeneratedFile[] = [];
	const memoryContract = memoryContractFor(skill);
	const executorRegistry = executorRegistrySnapshot();
	if (host === "pi") {
		files.push({
			path: join(root, "SKILL.md"),
			content: readFileSync(join(canonicalRoot, skill.instructions.pi_path)),
		});
		files.push({ path: join(root, "sure.skill.json"), content: jsonFile(piManifest(skill)) });
		files.push({ path: join(root, "hooks", "index.ts"), content: hookFacade(skill) });
	} else {
		files.push({ path: join(root, "SKILL.md"), content: Buffer.from(portableSkillMarkdown(skill), "utf8") });
		files.push({ path: join(root, "agents", "openai.yaml"), content: Buffer.from(openAiYaml(skill), "utf8") });
		files.push({
			path: join(root, "memory", "README.md"),
			content: Buffer.from(portableMemoryReadme(skill), "utf8"),
		});
		files.push({
			path: join(root, "semantic-backends.json"),
			content: jsonFile({
				schema: "sure.semantic.backends.v1",
				validators: skill.semantic_validators,
				resolution: "sure-core-registry",
				registry_digest: semanticBackendManifest.registry_digest,
				runtime_distribution_digest: semanticRuntimeDigest,
				bundles: semanticBackendManifest.bundles,
			}),
		});
		files.push({
			path: join(root, "references", "README.md"),
			content: Buffer.from(
				`# Bundled references\n\nThis directory contains host-neutral references selected from the canonical skill. ${resourceSet.omitted.length} legacy host/backend files are intentionally resolved by the pinned SURE Core registry instead of copied into a portable skill.\n`,
				"utf8",
			),
		});
	}
	files.push({
		path: join(root, "executor-registry.json"),
		content: jsonFile(executorRegistry),
	});
	if (host === "pi") {
		files.push({
			path: join(root, "semantic-backends.json"),
			content: jsonFile({
				schema: "sure.semantic.backends.v1",
				validators: skill.semantic_validators,
				resolution: "sure-core-registry",
				registry_digest: semanticBackendManifest.registry_digest,
				runtime_distribution_digest: semanticRuntimeDigest,
				bundles: semanticBackendManifest.bundles,
			}),
		});
	}
	const registry = materializedValidatorRegistry();
	files.push({
		path: join(root, "validator-registry.json"),
		content: jsonFile({
			schema: registry.schema,
			digest: registry.digest,
			validators: registry.validators.filter(
				(descriptor) => descriptor.skill_id === undefined || descriptor.skill_id === skill.skill_id,
			),
		}),
	});
	for (const resource of resourceSet.files) files.push({ path: join(root, resource.path), content: resource.content });
	files.push({ path: join(root, "memory-contract.json"), content: jsonFile(memoryContract) });
	const lock = lockFor(
		skill,
		host,
		resourceSet.files,
		resourceSet.omitted,
		semanticBackendManifest,
		memoryContract,
		semanticRuntimeDigest,
	);
	files.push({ path: join(root, "generation.lock.json"), content: jsonFile(lock) });
	files.push({
		path: join(root, "canonical-definition.json"),
		content: jsonFile(host === "portable" ? portableDefinition(skill) : skill),
	});
	return { files, lock };
}

function expectedFiles(): GeneratedFile[] {
	const files: GeneratedFile[] = [];
	files.push({ path: codingAgentWorkflowRegistry, content: workflowRegistryModule() });
	const semanticBackendManifest = materializedSemanticBackendManifest();
	const portableRuntime = portableRuntimeFiles(semanticBackendManifest);
	files.push(...portableRuntime.files);
	files.push({
		path: join(repositoryRoot, "sure", "canonical", "shared", "evaluation", "backend-manifest.json"),
		content: jsonFile(semanticBackendManifest),
	});
	files.push({
		path: join(repositoryRoot, "sure", "canonical", "shared", "memory-contract.json"),
		content: jsonFile(CANONICAL_MEMORY_CONTRACT),
	});
	files.push({
		path: join(repositoryRoot, "sure", "canonical", "shared", "executor-registry.json"),
		content: jsonFile(executorRegistrySnapshot()),
	});
	for (const skill of CANONICAL_SKILLS) {
		files.push(
			...buildHostFiles(skill, "pi", semanticBackendManifest, portableRuntime.lock.runtime_digest).files,
			...buildHostFiles(skill, "portable", semanticBackendManifest, portableRuntime.lock.runtime_digest).files,
		);
	}
	const registry = CANONICAL_SKILLS.map((skill) => ({
		skill_id: skill.skill_id,
		command_id: skill.command_id,
		pi_command: skill.pi.command,
		portable_slug: skill.distribution_slug,
		workflow_digest: canonicalJsonDigest(asJson(skill.workflow)),
	}));
	files.push({
		path: join(generatedPiRoot, "registry.json"),
		content: jsonFile({ schema: "sure.command.registry.v1", entries: registry }),
	});
	files.push({
		path: join(portableRoot, "registry.json"),
		content: jsonFile({ schema: "sure.command.registry.v1", entries: registry }),
	});
	const validatorRegistry = materializedValidatorRegistry();
	files.push({
		path: join(repositoryRoot, "sure", "canonical", "validators", "registry.json"),
		content: jsonFile(validatorRegistry),
	});
	const memoryEntries = ["sure_onboard", "sure_infer", "sure_eval", "sure_trans", "sure_feed"]
		.map((skillId) => CANONICAL_SKILLS.find((skill) => skill.skill_id === skillId))
		.filter((skill): skill is CanonicalSkillDefinition => skill !== undefined)
		.map((skill) => [
			skill.skill_id,
			skill.workflow.branches.flatMap((branch) => branch.units.map((unit) => unit.id)),
		]);
	const memoryDocument = { schema: "sure.memory.units.v1", skills: Object.fromEntries(memoryEntries) };
	files.push({
		path: join(repositoryRoot, "sure", "runtime", "memory", "units.json"),
		content: jsonFile(memoryDocument),
	});
	files.push({
		path: join(repositoryRoot, "sure", "runtime", "memory", "units.generation.lock.json"),
		content: jsonFile({
			schema: "sure.memory.units.generation.lock.v1",
			workflow_digests: Object.fromEntries(
				CANONICAL_SKILLS.filter((skill) => skill.skill_id !== "sure_approve").map((skill) => [
					skill.skill_id,
					canonicalJsonDigest(asJson(skill.workflow)),
				]),
			),
		}),
	});
	return files;
}

function markerPath(root: string): string {
	return join(root, GENERATED_MARKER);
}

function writeGenerated(files: readonly GeneratedFile[]): void {
	const roots = [generatedPiRoot, portableRoot, portableRuntimeRoot];
	for (const root of roots) {
		if (existsSync(root)) {
			if (!existsSync(markerPath(root))) throw new Error(`Refusing to replace unmarked generated root: ${root}`);
			rmSync(root, { recursive: true, force: true });
		}
		mkdirSync(root, { recursive: true });
		writeFileSync(markerPath(root), "sure generated; do not edit\n", "utf8");
	}
	for (const file of files) {
		mkdirSync(dirname(file.path), { recursive: true });
		writeFileSync(file.path, file.content);
	}
}

function actualFiles(root: string): string[] {
	return allFiles(root).filter((path) => path !== GENERATED_MARKER);
}

function checkGenerated(files: readonly GeneratedFile[]): void {
	const expected = new Map(files.map((file) => [file.path, file.content]));
	const problems: string[] = [];
	for (const [path, content] of expected) {
		if (!existsSync(path)) {
			problems.push(`missing ${relative(repositoryRoot, path)}`);
			continue;
		}
		if (!lstatSync(path).isFile() || !readFileSync(path).equals(content))
			problems.push(`stale ${relative(repositoryRoot, path)}`);
	}
	for (const root of [generatedPiRoot, portableRoot, portableRuntimeRoot]) {
		for (const path of actualFiles(root)) {
			const absolute = join(root, path);
			if (!expected.has(absolute)) problems.push(`unexpected ${relative(repositoryRoot, absolute)}`);
		}
	}
	if (problems.length > 0) throw new Error(`Generated SURE skill outputs are stale:\n${problems.join("\n")}`);
}

const files = expectedFiles();
if (process.argv.includes("--check")) {
	checkGenerated(files);
	console.log(`SURE skill generation is current (${files.length} files).`);
} else {
	writeGenerated(files);
	console.log(`Generated ${files.length} SURE Pi/portable skill files.`);
}
