import { defineCanonicalSkill } from "../../define.ts";
import type { CanonicalSkillDefinition } from "../../types.ts";

export const SURE_APPROVE_CANONICAL: CanonicalSkillDefinition = defineCanonicalSkill({
	schema: "sure.canonical.skill.v1",
	skill_id: "sure_approve",
	command_id: "sure-approve",
	distribution_slug: "sure-approve",
	display_name: "SURE Approve",
	description: "Audit and explicitly approve a completed model bundle for publication to SURE Eval.",
	workflow: {
		schema: "sure.workflow.definition.v1",
		workflow_id: "sure_approve",
		version: "legacy-v1",
		checkpoint_id: "approval_flow",
		checkpoint_label: "SURE approval state machine",
		branches: [
			{
				id: "audit",
				units: [
					{
						id: "resolve_input",
						label: "Resolve approval input",
						kind: "gate",
						produces: "approve_input_resolved.json",
						schema_ref: "approve_input_resolved.schema.json",
						required_fields: ["schema", "status", "mode", "source", "approval", "site_policy"],
						gate: {
							validator_id: "python-script",
							script_id: "resolve_approve_input.py",
						},
					},
					{
						id: "classify_producer",
						label: "Classify producer contract",
						kind: "gate",
						produces: "producer_contract_report.json",
						schema_ref: "producer_contract_report.schema.json",
						required_fields: [
							"schema",
							"status",
							"producer",
							"contract",
							"model_name",
							"runtime_kind",
							"findings",
						],
						gate: {
							validator_id: "python-script",
							script_id: "audit_bundle.py",
							script_args: ["--kind", "producer"],
						},
					},
					{
						id: "audit_integrity",
						label: "Audit bundle integrity",
						kind: "gate",
						produces: "integrity_report.json",
						schema_ref: "integrity_report.schema.json",
						required_fields: ["schema", "status", "source_digest", "checks", "findings"],
						gate: {
							validator_id: "python-script",
							script_id: "audit_bundle.py",
							script_args: ["--kind", "integrity"],
						},
					},
					{
						id: "plan_repairs",
						label: "Plan bounded repairs",
						kind: "gate",
						produces: "repair_plan.json",
						schema_ref: "repair_plan.schema.json",
						required_fields: ["schema", "status", "repair_mode", "safe_repairs", "rerun_required"],
						gate: {
							validator_id: "python-script",
							script_id: "plan_repairs.py",
						},
					},
					{
						id: "apply_repairs",
						label: "Create isolated candidate",
						kind: "gate",
						produces: "repair_report.json",
						schema_ref: "repair_report.schema.json",
						required_fields: [
							"schema",
							"status",
							"candidate_dir",
							"source_digest_before",
							"source_digest_after",
							"repairs_applied",
						],
						gate: {
							validator_id: "python-script",
							script_id: "apply_safe_repairs.py",
						},
					},
					{
						id: "seal_candidate",
						label: "Seal candidate identity",
						kind: "gate",
						produces: "approval_manifest.json",
						schema_ref: "approval_manifest.schema.json",
						required_fields: ["schema", "status", "model_name", "candidate_dir", "candidate_digest", "files"],
						gate: {
							validator_id: "python-script",
							script_id: "build_approval_manifest.py",
							script_args: ["--kind", "manifest"],
						},
					},
					{
						id: "verify_runtime",
						label: "Verify candidate runtime",
						kind: "gate",
						produces: "runtime_verification.json",
						schema_ref: "runtime_verification.schema.json",
						required_fields: ["schema", "status", "runtime_kind", "binding", "smoke"],
						gate: {
							validator_id: "python-script",
							script_id: "verify_candidate_runtime.py",
						},
					},
					{
						id: "prepare_review",
						label: "Prepare human review",
						kind: "gate",
						produces: "review_packet.json",
						schema_ref: "review_packet.schema.json",
						required_fields: [
							"schema",
							"status",
							"model_name",
							"candidate_dir",
							"candidate_digest",
							"approval_manifest_sha256",
							"site_policy_sha256",
							"findings",
							"packet_digest",
						],
						gate: {
							validator_id: "python-script",
							script_id: "build_approval_manifest.py",
							script_args: ["--kind", "review"],
						},
					},
				],
				initial_unit_id: "resolve_input",
				terminal_unit_id: "prepare_review",
			},
			{
				id: "approve",
				units: [
					{
						id: "verify_decision",
						label: "Verify human decision",
						kind: "gate",
						produces: "approval_decision.json",
						schema_ref: "approval_decision.schema.json",
						required_fields: [
							"schema",
							"status",
							"decision",
							"review_packet",
							"review_packet_digest",
							"candidate_digest",
							"actor",
						],
						gate: {
							validator_id: "python-script",
							script_id: "verify_human_decision.py",
						},
					},
					{
						id: "publish",
						label: "Publish approved bundle",
						kind: "gate",
						produces: "publication_result.json",
						schema_ref: "publication_result.schema.json",
						required_fields: ["schema", "status", "destination", "candidate_digest", "eval_visible"],
						gate: {
							validator_id: "python-script",
							script_id: "publish_approved_bundle.py",
						},
					},
					{
						id: "verify_publication",
						label: "Verify published bundle",
						kind: "gate",
						produces: "approval_ready.json",
						schema_ref: "approval_ready.schema.json",
						required_fields: [
							"schema",
							"status",
							"destination",
							"candidate_digest",
							"eval_visible",
							"deployment_binding",
						],
						gate: {
							validator_id: "python-script",
							script_id: "verify_published_bundle.py",
						},
					},
				],
				initial_unit_id: "verify_decision",
				terminal_unit_id: "verify_publication",
			},
		],
		default_branch_id: "audit",
		retry_policy: {
			default_max_retries: 3,
		},
	},
	unit_outputs: [
		{
			type: "unit.resolve_input",
			path: "artifacts/approve_input_resolved.json",
			required: true,
			description: "Output required before advancing from resolve_input.",
			scope: "run-local",
			publication_mode: "run-local",
			owner: "validator",
		},
		{
			type: "unit.classify_producer",
			path: "artifacts/producer_contract_report.json",
			required: true,
			description: "Output required before advancing from classify_producer.",
			scope: "run-local",
			publication_mode: "run-local",
			owner: "validator",
		},
		{
			type: "unit.audit_integrity",
			path: "artifacts/integrity_report.json",
			required: true,
			description: "Output required before advancing from audit_integrity.",
			scope: "run-local",
			publication_mode: "run-local",
			owner: "validator",
		},
		{
			type: "unit.plan_repairs",
			path: "artifacts/repair_plan.json",
			required: true,
			description: "Output required before advancing from plan_repairs.",
			scope: "run-local",
			publication_mode: "run-local",
			owner: "validator",
		},
		{
			type: "unit.apply_repairs",
			path: "artifacts/repair_report.json",
			required: true,
			description: "Output required before advancing from apply_repairs.",
			scope: "run-local",
			publication_mode: "run-local",
			owner: "validator",
		},
		{
			type: "unit.seal_candidate",
			path: "artifacts/approval_manifest.json",
			required: true,
			description: "Output required before advancing from seal_candidate.",
			scope: "run-local",
			publication_mode: "run-local",
			owner: "validator",
		},
		{
			type: "unit.verify_runtime",
			path: "artifacts/runtime_verification.json",
			required: true,
			description: "Output required before advancing from verify_runtime.",
			scope: "run-local",
			publication_mode: "run-local",
			owner: "validator",
		},
		{
			type: "unit.prepare_review",
			path: "artifacts/review_packet.json",
			required: true,
			description: "Output required before advancing from prepare_review.",
			scope: "run-local",
			publication_mode: "run-local",
			owner: "validator",
		},
		{
			type: "unit.verify_decision",
			path: "artifacts/approval_decision.json",
			required: true,
			description: "Output required before advancing from verify_decision.",
			scope: "run-local",
			publication_mode: "run-local",
			owner: "validator",
		},
		{
			type: "unit.publish",
			path: "artifacts/publication_result.json",
			required: true,
			description: "Output required before advancing from publish.",
			scope: "run-local",
			publication_mode: "run-local",
			owner: "validator",
		},
		{
			type: "unit.verify_publication",
			path: "artifacts/approval_ready.json",
			required: true,
			description: "Output required before advancing from verify_publication.",
			scope: "run-local",
			publication_mode: "run-local",
			owner: "validator",
		},
	],
	internal_evidence: [
		{
			type: "checkpoint",
			path: "state.json",
			required: true,
			description: "Legacy-compatible checkpoint projection.",
			scope: "run-local",
			publication_mode: "run-local",
			owner: "harness",
		},
		{
			type: "event_log",
			path: "events.jsonl",
			required: true,
			description: "Append-only lifecycle and validator events.",
			scope: "run-local",
			publication_mode: "append-only",
			owner: "harness",
		},
	],
	published_artifacts: [
		{
			type: "review_packet",
			path: "artifacts/review_packet.json",
			required: false,
			description: "Human review packet bound to the immutable audit candidate.",
			scope: "run-local",
			publication_mode: "run-local",
			owner: "agent",
		},
		{
			type: "approval_decision",
			path: "artifacts/approval_decision.json",
			required: false,
			description: "Explicit human approval or rejection bound to the review packet.",
			scope: "run-local",
			publication_mode: "run-local",
			owner: "agent",
		},
		{
			type: "approval_ready",
			path: "artifacts/approval_ready.json",
			required: false,
			description: "Verified atomic publication marker consumable by the current Eval deployment binding.",
			scope: "run-local",
			publication_mode: "run-local",
			owner: "agent",
		},
	],
	capabilities: [
		{
			capability_id: "sure.execution.site-publication",
			capability_class: "execution_capability",
			required: true,
			description: "Site policy and an approved publication root.",
		},
		{
			capability_id: "sure.execution.human-approval",
			capability_class: "execution_capability",
			required: true,
			description: "Explicit human decision bound to the review packet.",
		},
	],
	semantic_validators: [
		{
			id: "python-script",
			operation: "validate",
			script: "resolve_approve_input.py",
			description: "Semantic validator python-script registered by the resolve_input gate.",
		},
	],
	instructions: {
		common_path: "instructions.common.md",
		portable_path: "instructions.portable.md",
		pi_path: "instructions.pi.md",
	},
	resources: {
		directories: ["scripts", "schemas", "references", "examples"],
		legacy_root: "sure/skills/sure_approve",
	},
	pi: {
		name: "sure_approve",
		command: "/sure_approve",
		description:
			"Audit and explicitly approve a completed onboard or trans bundle for atomic publication to SURE Eval.",
		prompt: "SKILL.md",
		hooks: {
			pre_start: [
				{
					module: "hooks/index.ts",
					handler: "preStart",
				},
			],
			pre_tool_call: [
				{
					module: "hooks/index.ts",
					handler: "preToolCall",
				},
			],
			post_tool_result: [
				{
					module: "hooks/index.ts",
					handler: "postToolResult",
				},
			],
			pre_finish: [
				{
					module: "hooks/index.ts",
					handler: "preFinish",
				},
			],
			post_finish: [
				{
					module: "hooks/index.ts",
					handler: "postFinish",
				},
			],
			on_error: [
				{
					module: "hooks/index.ts",
					handler: "onError",
				},
			],
		},
		ui: {
			primaryCounters: ["completed_units", "total_units", "gate_blocks"],
			artifactTypes: ["review_packet", "approval_decision", "approval_ready"],
			defaultExpandedSections: ["diagnostics", "artifacts"],
		},
	},
});

export default SURE_APPROVE_CANONICAL;
